#!/bin/bash

## For lazily uploading git things
## To code repository
## Will work if already upstream task set
## to remote repository
## Author : Sandip Dutta

echo -e "Uploading to $(git remote get-url origin)\n"

# remove executables, reject rm output for empty removal
# code mainly in python and c++, so these two
ls | grep -vE "(\.cpp$|\.py|\.md|lazygit$)"| xargs rm 2> /dev/null

echo "Removed Executable Files"

git add .

today_date=$(date +%D)

message="New Problems Added"

if [ $# -gt 0 ]
then
	message=$1
fi

git commit -m "$today_date - $message"
git push
echo -e "\nPushing Successful..."
